### ISSUE TITLE
No Error Check Causes "invisible" inventory items

### ISSUE THREAD

**Issue by DivineInsanity** [elgbar/instant-inventory#1]
Noticed when using this plugin that one time I dropped 2 logs while mid-animation entering Kharazi jungle.

Because of this the client side update from this plugin "removed" them from my inventory, but they were infact still there. So possibly needs to check if the drop actually happened and if not, revert the client side change. 

Opening the bank alerted me to this as they now became visible, but even banking and re-withdrawing them did not update the client side. Had to disable plugin, then bank/re-withdraw.

**Comment by elgbar** [comment]
This is already fixed in `v1.0.1`! (the version needs to be be approved by the runelite team)

Items which does not change in two ticks (1,2 seconds) will be reverted to the correct state.

Sorry for the inconvenience
