### ISSUE TITLE
shift click wear bug

### ISSUE THREAD

**Issue by tig99** [elgbar/instant-inventory#13]
**Describe the bug**
When you have an item set to shift click wear with menu entry swapper and the instant equip feature on, the item will not equip. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Click on '....'
2. See error
menu entry swap a piece of armor to shift click equip.
enable equip items instantly in the instant inventory plugin settings
shift click the piece of armor to equip in your inventory
the item does not equip

**Expected behaviour**
the item should equip
**Screenshots**
If applicable, add screenshots/video to help explain your problem.

**Additional context**

**Comment by elgbar** [comment]
I have confirmed this in-game, sorry for the inconvenience.

**Comment by elgbar** [comment]
**steps to reproduce**
1. Swap `Wield`/`Equip` etc. with `Use` with the menu swapper plugin
2. Try to equip the item while holding shift
3. The items disappears for a tick
4. The item is not equipped

**Comment by elgbar** [comment]
Closed by https://github.com/elgbar/instant-inventory/pull/15
