### ISSUE TITLE
Tileman-Async-Mode

### ISSUE THREAD

**Issue by Spigotron** [elgbar/instant-inventory#19]
Hello sir,

My issue isn't related to Instant Inventory. I apologize, but I couldn't figure out any other way to contact you. I am in desperate need of your Tileman-Async-Mode plugin; Tileman mode has become virtually unplayable for me, after unlocking tens of thousands of tiles. Is there any way I can use that code/plugin? I have already tried myself, with IntelliJ, but to no avail. Many thanks.

- Spigotron

**Comment by elgbar** [comment]
I've been your message on the tilebound discord, let's continue the conversation there
