### ISSUE TITLE
Dropping items that check to confirm via dialog box cause item to become invisible

### ISSUE THREAD

**Issue by b-licorice** [elgbar/instant-inventory#3]
I've noticed that any items that open a dialog box to warn/verify that you want to drop (e.g. based on the limit set in-game) hide the item immediately regardless of whether the drop is confirmed or not. This is especially problematic if you are mid-combat and the dialog box gets interrupted, as it effectively causes the item to disappear from your inventory.

To prevent similar issues, I think following each "hide" action with an inventory state check at the next game tick in order to verify synchronization may help to minimize these sorts of errors, especially if support for gear switches is intended to be added in the near future. It would be very unfortunate to have certain crucial items accidentally become inaccessible from your inventory during difficult PvM and PvP situations.

**Comment by elgbar** [comment]
Yeah sorry about this issue. It is fixed in v1.0.1, but it takes some time for the runelite team to approve the changes :shrug: 

Also it's already rapported in #1
