### ISSUE TITLE
Instantly swap equipment

### ISSUE THREAD

**Issue by elgbar** [elgbar/instant-inventory#5]
Hide as dropped if the equal slot is empty
Swap with current equipped item if there is something in the slot (and you can equip it)

**Comment by alizan** [comment]
Any update on this suggested feature? Was just about to make same suggestion. It gives a much better gameplay feel when things respond instantly!

**Comment by elgbar** [comment]
No progress have been made yet, I've been busy with life. I would be happy for a PR

**Comment by alizan** [comment]
That's fair, I'm no developer but I might check in the Runelite discord. Enjoy irl!

**Comment by elgbar** [comment]
Closed by v1.2.0
