### ISSUE TITLE
Dropping lightsource in dark areas

### ISSUE THREAD

**Issue by IanTBrown** [elgbar/instant-inventory#6]
Dropping any light source in a dark area gives the message "Dropping that would leave you without a light source" from the runescape client and prevents the item from being removed from your inventory.

If I decide to enter a dark area, such Tears of Guthix or the Tunnel in Lumby castle basement, and drop my light source then the inventory spot appears empty, but i may not swap with this inventory spot or pick up any additional items. In order to fix it I have to go to a bank, deposit the item (it appears in a bank window), CLOSE THE BANK, then access the bank again and retrieve my item.

Almost thought I had to buy another firemaking cape, scared the shit out of me man! lol

I appreciate your plugin so I just wanted to take this time to additionally thank you for your work on it. This bug is pretty preventable by not being a dingus so don't worry too much about it!

**Comment by elgbar** [comment]
Yeah, sorry for the bug, it's the same bug as #1.
It is fixed in the next version, but the runelite team is slow to approve the next version.

**Comment by IanTBrown** [comment]
Thank you
