### ISSUE TITLE
Plugin conflict with any other item hiding plugin

### ISSUE THREAD

**Issue by CreativeTechGuy** [elgbar/instant-inventory#8]
I received [a report for my plugin not working](https://github.com/CreativeTechGuy/no-bad-alchs/issues/1). It seems like it's a conflict with your plugin. I looked into it, and it seems that your plugin will override any other plugin which attempts to hide items.

[This is the offending section of code](https://github.com/elgbar/instant-inventory/blob/master/src/main/java/no/elg/ii/feature/hide/HideFeature.java#L78-L93) which forcefully hides/shows items based on your set of rules.

Is there a way that your plugin can respect items hidden by other plugins? Something like, if an item's visibility changes, and you didn't change it, then you don't mess with it?

Happy to work together to figure out a solution. But this seems like an issue that is wider than just between our two plugins.

**Comment by CreativeTechGuy** [comment]
Another suggestion which might work is similar to what I'm doing for showing/hiding items. I'll keep track of each item I've hidden, and when I want to reshow everything, I'll only toggle the hidden state on the items which I have in my list. Not sure if this will work for your plugin, but could be an easy solution. It seems like the forcefully showing part is the issue so as long as you only show items which your plugin has hidden, it should be okay.

**Comment by elgbar** [comment]
Thanks for letting me know, I think the solution is as you say now wildly hide/unhide items.

What might be missing from my side is a third state apart from should be shown and should be hidden. I didn't really considered that other plugins might hide items as well :p

**Comment by CreativeTechGuy** [comment]
Hey @elgbar it looks like this is still an issue. Are you able to update your plugin to fix the incompatibility? Thanks!

**Comment by elgbar** [comment]
Yeah, sorry about the long delay. I'm currently looking into how to fix this issue properly (take a look at the dev branch)

**Comment by CreativeTechGuy** [comment]
Thank you!

**Comment by elgbar** [comment]
Fixed in v1.1.2

**Comment by CreativeTechGuy** [comment]
Oh awesome! Appreciate it. :)
