### ISSUE TITLE
More intelligent deposit item into bank for stacks

### ISSUE THREAD

**Issue by orlp** [elgbar/instant-inventory#9]
When depositing items into the bank, it would be nice if the plugin was more intelligent about item stacks / noted items.

If I'm depositing 10 items from a stack of 20 I don't want the stack to disappear. It would be extra fancy if it instantly updated the count to 10, but that's not as pressing of a request as not making the stack disappear.

**Comment by elgbar** [comment]
Duplicate of #7 

I've already done what you've suggested! [It just hasn't been approved by the runelite team yet](https://github.com/runelite/plugin-hub/pull/4253)

**Comment by orlp** [comment]
I see, I should've searched beforehand. My bad.
